version: "3.9"

services:
  streaming-app-db:
    container_name: streaming-app-db
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  dispatcher:
    container_name: dispatcher
    depends_on:
      - streaming-app-db
    restart: on-failure
    image: dispatcher
    build: /dispatcher/.
    ports:
      - ${DISPATCHER_PORT}:${DISPATCHER_PORT}
    expose:
      - ${DISPATCHER_PORT}
    environment:
      - DISPATCHER_PORT=${DISPATCHER_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=streaming-app-db
      - DB_PORT=${DB_PORT}
