spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: dispatcher
          uri: lb://DISPATCHER
          predicates:
            - Path=/dispatcher/**
          filters:
            - StripPrefix=1
            - AuthFilter

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

server:
  port: ${API_GATEWAY_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/