jwt:
  secret: CRClPakWbPafJH12umy4hdV4MNNeutKv62UjIsg278Uh4nfj7sfhefHUFIWAyhfisfs83h23qwr29r32r
  expiration: 6000000

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: security-service

server:
  port: ${SECURITY_SERVICE_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/