server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgres://localhost:5432/stream_app
    username: postgres
    password: postgres
    driver-class: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
