server:
  port: ${EUREKA_PORT}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: eureka-service